spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/account_processing_db
    username: postgres
    password: 2003
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true
        format_sql: true
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/master.xml

  kafka:
    bootstrap-servers: localhost:29092
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "ru.t1.dto"

server:
  port: 8082