spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/client_processing_db
    username: postgres
    password: 2003
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true
        format_sql: true
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/master.xml

  kafka:
    # Адрес брокера Kafka, к которому будет подключаться Spring
    bootstrap-servers: localhost:29092
    admin:
      auto-create: true
    producer:
      # Превращает ключ сообщения в байты
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      # Превращает объект Java в JSON (для Kafka)
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    properties:
      spring.json.add.type.headers: true


app:
  service-name: client-processing
  kafka:
    topics:
      client-products: client_products
      client-credit-products: client_credit_products
      client-cards: client_cards
      service-logs: service_logs

metric:
  execution-limit-ms: 100

cache:
  ttl-ms: 60000

server:
  port: 8081