spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/credit_processing_db
    username: postgres
    password: 2003
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true
        format_sql: true
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/master.xml

  kafka:
    bootstrap-servers: localhost:29092
    admin:
      auto-create: true
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "ru.t1.dto"
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    properties:
      spring.json.add.type.headers: true

credit:
  limit: 2000000 # пример: 2 млн
  interestRate: 22 # пример: 22%
  monthCount: 60 # пример: 60 месяцев (5 лет)
  amount: 100000 # пример: 100 000

app:
  service-name: credit-processing
  kafka:
    topics:
      service-logs: service_logs

metric:
  execution-limit-ms: 10000

cache:
  ttl-ms: 60000

server:
  port: 8083